"use client";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { CasePacketRecord } from "@/types/workspace";

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function getSummary(packet: CasePacketRecord): Record<string, unknown> | null {
  return isObject(packet.summary_payload) ? packet.summary_payload : null;
}

function getChecklistCount(packet: CasePacketRecord): number {
  return Array.isArray(packet.checklist_payload) ? packet.checklist_payload.length : 0;
}

function getIndexCount(packet: CasePacketRecord): number {
  return Array.isArray(packet.document_index) ? packet.document_index.length : 0;
}

export function PacketSummaryCard({ packet }: { packet: CasePacketRecord }): JSX.Element {
  const summary = getSummary(packet);

  return (
    <Card title="Packet Summary" subtitle="Latest generated review package for this case">
      <div className="page-stack">
        <div className="case-hero__badges">
          <Badge tone="info">{packet.packet_status}</Badge>
          <Badge tone="neutral">v{packet.packet_version}</Badge>
        </div>

        <dl className="ui-key-values">
          <div>
            <dt>Generated At</dt>
            <dd>{new Date(packet.generated_at).toLocaleString()}</dd>
          </div>
          <div>
            <dt>Generated By</dt>
            <dd>{packet.generated_by_reference ?? "Not provided"}</dd>
          </div>
          <div>
            <dt>Document Index</dt>
            <dd>{getIndexCount(packet)}</dd>
          </div>
          <div>
            <dt>Checklist Items</dt>
            <dd>{getChecklistCount(packet)}</dd>
          </div>
        </dl>

        {summary ? (
          <div className="entity-card__meta">
            <p>Case number: {String(summary.case_number ?? "Not available")}</p>
            <p>Case type: {String(summary.case_type ?? "Not available")}</p>
            <p>Case status: {String(summary.case_status ?? "Not available")}</p>
            <p>Open inconsistencies: {String(summary.open_inconsistency_count ?? "0")}</p>
          </div>
        ) : null}

        {packet.generation_notes ? <p className="entity-card__hint">{packet.generation_notes}</p> : null}
      </div>
    </Card>
  );
}
