"use client";

import { useState } from "react";

import { PermissionGate } from "@/components/auth/permission-gate";
import { PacketSummaryCard } from "@/components/packet/packet-summary-card";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { generateCasePacket } from "@/services/packet";
import { ApiErrorPayload } from "@/types/api";
import { CasePacketRecord } from "@/types/workspace";

interface PacketPanelProps {
  caseId: string;
  packet: CasePacketRecord | null;
  loading: boolean;
  error: ApiErrorPayload | null;
  onRefresh: () => Promise<void>;
}

function getErrorMessage(error: unknown): string {
  const apiError = error as ApiErrorPayload;
  if (typeof apiError?.detail === "string") {
    return apiError.detail;
  }
  return apiError?.message ?? "Could not generate packet.";
}

function packetIndex(packet: CasePacketRecord): Array<Record<string, unknown>> {
  return Array.isArray(packet.document_index) ? (packet.document_index as Array<Record<string, unknown>>) : [];
}

function packetChecklist(packet: CasePacketRecord): Array<Record<string, unknown>> {
  return Array.isArray(packet.checklist_payload) ? (packet.checklist_payload as Array<Record<string, unknown>>) : [];
}

function exportArtifact(packet: CasePacketRecord): Record<string, unknown> | null {
  return typeof packet.export_artifact === "object" && packet.export_artifact !== null && !Array.isArray(packet.export_artifact)
    ? (packet.export_artifact as Record<string, unknown>)
    : null;
}

export function PacketPanel({ caseId, packet, loading, error, onRefresh }: PacketPanelProps): JSX.Element {
  const [generatedByReference, setGeneratedByReference] = useState("");
  const [generationNotes, setGenerationNotes] = useState("");
  const [busy, setBusy] = useState(false);
  const [panelError, setPanelError] = useState<string | null>(null);
  const [panelMessage, setPanelMessage] = useState<string | null>(null);

  async function handleGenerate(): Promise<void> {
    setBusy(true);
    setPanelError(null);
    setPanelMessage(null);

    try {
      await generateCasePacket({
        caseId,
        generatedByReference: generatedByReference || undefined,
        generationNotes: generationNotes || undefined,
      });
      await onRefresh();
      setPanelMessage("Packet generated successfully.");
    } catch (generateError) {
      setPanelError(getErrorMessage(generateError));
    } finally {
      setBusy(false);
    }
  }

  if (loading) {
    return <LoadingState label="Loading packet..." />;
  }

  if (error && !packet) {
    return (
      <ErrorState
        title="Could not load packet"
        description="The packet data could not be retrieved from the backend."
      />
    );
  }

  const index = packet ? packetIndex(packet) : [];
  const checklist = packet ? packetChecklist(packet) : [];
  const artifact = packet ? exportArtifact(packet) : null;

  return (
    <div className="detail-sections">
      <div className="entity-card">
        <div className="entity-card__header">
          <strong>Generate Packet</strong>
          <p>Create or refresh the case packet from current documents, canonical fields and reviews.</p>
        </div>

        <div className="entity-card__grid">
          <label className="ui-field">
            <span>Generated By Reference</span>
            <input
              value={generatedByReference}
              onChange={(event) => setGeneratedByReference(event.target.value)}
              placeholder="staff.user"
            />
          </label>

          <label className="ui-field entity-card__field-span">
            <span>Generation Notes</span>
            <input
              value={generationNotes}
              onChange={(event) => setGenerationNotes(event.target.value)}
              placeholder="Notes for this packet generation"
            />
          </label>
        </div>

        {panelError ? <p className="document-feedback document-feedback--error">{panelError}</p> : null}
        {panelMessage ? <p className="document-feedback document-feedback--success">{panelMessage}</p> : null}

        <PermissionGate
          action="generate_packet"
          fallback={<p className="entity-card__hint">Your role cannot generate case packets.</p>}
        >
          <button type="button" className="ui-button" disabled={busy} onClick={() => void handleGenerate()}>
            {busy ? "Generating..." : "Generate packet"}
          </button>
        </PermissionGate>
      </div>

      {!packet ? (
        <EmptyState
          title="No packet generated"
          description="Generate a packet to review its summary, document index, checklist and export artifact."
        />
      ) : (
        <>
          <PacketSummaryCard packet={packet} />

          <div className="detail-sections detail-sections--two-columns">
            <div className="entity-card">
              <div className="entity-card__header">
                <strong>Document Index</strong>
                <p>Ordered documents included in the packet.</p>
              </div>

              {index.length ? (
                <div className="page-stack">
                  {index.map((item, indexPosition) => (
                    <div key={`${String(item.document_id ?? indexPosition)}-${indexPosition}`} className="placeholder-note">
                      <strong>{String(item.title ?? item.document_type ?? "Document")}</strong>
                      <p>
                        {String(item.section ?? "General")} | {String(item.document_status ?? "unknown")} | priority{" "}
                        {String(item.priority ?? "-")}
                      </p>
                    </div>
                  ))}
                </div>
              ) : (
                <EmptyState
                  title="Empty document index"
                  description="The packet exists but the backend did not return indexed documents."
                />
              )}
            </div>

            <div className="entity-card">
              <div className="entity-card__header">
                <strong>Checklist</strong>
                <p>Readiness checklist captured in the packet payload.</p>
              </div>

              {checklist.length ? (
                <div className="page-stack">
                  {checklist.map((item, indexPosition) => (
                    <div key={`${String(item.item_key ?? indexPosition)}-${indexPosition}`} className="placeholder-note">
                      <strong>{String(item.label ?? item.item_key ?? "Checklist item")}</strong>
                      <p>
                        {String(item.status ?? "unknown")} | required {String(item.required ?? true)} |{" "}
                        {String(item.related_document_type ?? "general")}
                      </p>
                    </div>
                  ))}
                </div>
              ) : (
                <EmptyState
                  title="Empty checklist"
                  description="The packet exists but no checklist items were returned by the backend."
                />
              )}
            </div>
          </div>

          <div className="entity-card">
            <div className="entity-card__header">
              <strong>Export Artifact</strong>
              <p>Exportable payload exposed by the backend for this packet.</p>
            </div>

            {artifact ? (
              <pre className="entity-card__evidence">{JSON.stringify(artifact, null, 2)}</pre>
            ) : (
              <EmptyState
                title="No export artifact"
                description="The backend did not expose an export artifact for this packet."
              />
            )}
          </div>
        </>
      )}
    </div>
  );
}
